defaultSemverRangePrefix: ''

enableScripts: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

supportedArchitectures:
  os:
    - linux

yarnPath: .yarn/releases/yarn-3.3.1.cjs
