name: CI - CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    name: Checks & deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Check - Yarn dedupe
        run: yarn dedupe -c

      - name: Check - Lint
        run: yarn c:lint

      - name: Check - Type
        run: yarn c:type

      - name: Check - Tests
        run: yarn c:test

      - name: Build
        run: yarn build

      - name: Publish to NPM (dry-run on PR)
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: ${{ github.ref != 'refs/heads/master' }}
